### PR TITLE
feat: Pre Authenticated Sessions

### PR DESCRIPTION
**Pull request by hdishner-ccc**
BEGIN_COMMIT_OVERRIDE
feature: Pre Authenticated Sessions (#31)

fix!: Remove unused UserManager parameter from the SessionStorage implementation constructors (#31)

refactor!: Renamed SessionManager to SessionStorage. This impacted public constructors (#31)
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by zredinger-ccc** [comment]
Hey @hdishner-ccc , I am curious. What are you thinking for the handlers and middleware on this? Is that something that is coming?

**Comment by jwatson-ccc** [comment]
@Hunter 

The implementation of `SpannerPreauthSessionManager` looks to be good. This is the storage driver that will get passed into our new `PreauthSession`.

`PreauthSpannerSession` is a little off the rails. It looks to be an implementation of `PreauthSession` that is hard-coded to spanner instead of allowing us to pass in a storage driver so it can be used with any database.

I will be pushing up a few commits to get this back on track.

**Comment by zredinger-ccc** [comment]
Seems like there are several things we will need to support with this implementation

- creating the session when the username is submitted
- validating the session. redirect back to login if it is invalid
- adding and updating session metadata
- clearing session metadata

Can we add a generic field in the db that is just JSON for metadata?

**Comment by jwatson-ccc** [comment]
> Seems like there are several things we will need to support with this implementation
> 
> * creating the session when the username is submitted
> * validating the session. redirect back to login if it is invalid
> * adding and updating session metadata
> * clearing session metadata
> 
> Can we add a generic field in the db that is just JSON for metadata?

My updates should address all the session management items. 
 - After completing the login workflow, the session will be created using the `NewSession()` method.
 - I was assuming we would be creating an Angular App for DLH. If so, the App will handle the redirection back to login once it receives the `401` from the API.
 - We should discuss how this library might be extended to store generic session data. My initial direction and thoughts were that we would store session data outside of this library. This way each app could customize what needs to be stored, and it would be stored under the sessionID in a standalone table. The drawback to that is you will then need to manage the data retention in that table.

Spanner has a nice [TTL feature](https://cloud.google.com/spanner/docs/ttl)

**Comment by hdishner-ccc** [comment]
I'm good to merge this is you are @zredinger-ccc @jwatson-ccc . I'm the opener though so I can't really put an "approval" per say

**Comment by jwatson-ccc** [comment]
We should shore up the new code with unit tests.

These test should be very similar to existing tests for the other implementation, so I hope it would quick

**Comment by hdishner-ccc** [comment]
@jwatson-ccc @zredinger-ccc  the tests for preauth implementations are written. If we can I'd like to do any other tests under another ticket. That way I can move on to more feature development in DLH.

**Review by jwatson-ccc — DISMISSED** [review]
LGTM

**Review by jwatson-ccc — APPROVED** [review]
LGTM

**Pull request merged**
